config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum:50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  
  def new
    @article = Article.new
  end
  
  def edit
  end
  
  def update
    if @article.update(article_params)
      flash[:notice] = "article successfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "article successfully saved"
      redirect_to article_path(@article)
    else
      render :new
    end
  end
  
  def show
  end
  
  def index
    @articles = Article.all
  end
  
  def destroy
      @article.destroy
      flash[:notice] = 'article was successfully deleted'
      redirect_to articles_path
  end
  
  private 
  
    def article_params
      params.require(:article).permit(:title, :description)
    end 
    
    def set_article
      @article = Article.find(params[:id])
    end 
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
  
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors occurred:</h2>
<ul>
<% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%=  f.submit%>
  </p>
  
  <p>
    <%= link_to 'back to article list', articles_path %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All articles</h1>
<p><%= link_to 'Create new article', new_article_path%></p>
<p>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td><%= link_to article.title, article_path(article) %></td>
    <td><%= article.description %></td>
    <td><%= link_to 'edit', edit_article_path(article) %></td>
    <td><%= link_to 'delete', article_path(article), method: :delete, data: { confirm: 'are you sure?' } %></td>
  </tr>
  <% end %>
</table>
</p>

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Selected article</h1>

<p>Title: <%= @article.title %></p>

<p>Description: <%= @article.description %></p>

<p><%= link_to 'back to article list', articles_path %> | <%= link_to 'edit this article', edit_article_path(@article)%></p>

app/views/layouts/_messages.html.erb
<ul>
  <% flash.each do |k, v| %>
  <li><%= v %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page, dumbass.</h1>
<%= link_to image_tag('Sam_about.gif') %>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>This is the home page, dickhead</h1>
<%= link_to image_tag('Yosemite_Sam.gif') %>
<%= link_to 'Alpha Blog', articles_path %> | <%= link_to 'About', about_path %>